language: node_js
sudo: false
node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'
addons:
  code_climate:
    repo_token: 68ddbd40159f9e23938004b7d52767f3488e976d1b77c5649b88064eff8ac06c
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
